### ISSUE TITLE
Zmena rozsahu

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/GEODOS01#22]
Vedci chteli upravit detekcni rozsah, tak je treba do vsech novych kusu osazovat odpor R10 12k misto 6k8. Na modulu fotonasobice.

![270041747_627895475193995_7953880010693752277_n](https://user-images.githubusercontent.com/1194177/147774092-81567af1-eb24-4752-8a27-cc0261119351.png)

Puvodne byl rozsah do cca 35 MeV. Ted je neco kolem 15 MeV.

**Comment by ChroustJan** [comment]
Změna zaznamenána do schéma pro další výrobu: https://github.com/UniversalScientificTechnologies/AIRDOSC01/blob/AIRDOSC01A/hw/sch_pcb/AIRDOSC01A_PCB01C/hw/sch_pcb/AIRDOSC01A_PCB01C.pdf
