### ISSUE TITLE
Vyřešení potíží s novou verzí obvodu BQ34Z100

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/GEODOS01#7]
Nově vyrobené moduly LION1CELL01jsou osazeny novou verzí obvodu [BQ34Z100](https://www.ti.com/product/BQ34Z100) označovanou jako [BQ34Z100-G1](https://www.ti.com/product/BQ34Z100-G1). 

Oba čipy se  vzájemně liší [zřejmě hlavně firmwarem](https://e2e.ti.com/support/power-management/f/power-management-forum/653763/bq34z100-g1-bq34z100-to-bq34z100-g1-change-list).  Zřejmě existuje možnost do nového čipu nahrát starý firmware. Dělá se to [pravděpodobně přes I2C](https://e2e.ti.com/support/power-management/f/power-management-forum/464735/bq34z100-g-in-system-flash-programming-help).

**Comment by kaklik** [comment]
Existuje několik knihoven pro Arduino, které by měly umět zacházet s oběma typy obvodů: 

- https://github.com/xkam1x/BQ34Z100G1
- https://github.com/tony-cloud/BQ34Z100
- https://github.com/Ralim/BQ34Z100

**Comment by kakl** [comment]
FW pocita s novou verzi BQ34Z100-G1
nastaveni nove verze se dela pres FW pro datalogger

**Comment by kaklik** [comment]
Obvod se nastavuje [tímto firmwarem](https://github.com/ODZ-UJF-AV-CR/GEODOS01/blob/GEODOS01A/fw/guage_setup/guage_setup.ino).
